#!/bin/bash

name=extract-chrome-cookies

latest_version=$(curl -L -s -H 'Accept: application/json' https://github.com/lei4519/$name/releases/latest | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')

download_url=https://github.com/lei4519/$name/releases/download/$latest_version/$name.tar.gz
 
cd $HOME

mkdir -p .$name

cd .$name

curl -fsSLO $download_url

tar -xzvf $name.tar.gz

mkdir -p /usr/local/bin
ln -fbs $name /usr/local/bin/$name

mkdir -p /usr/local/share/zsh/site-functions 
ln -fbs _$name /usr/local/share/zsh/site-functions/_$name

mkdir -p /usr/local/share/bash-completion/completions 
lb -fbs $name.bash /usr/local/share/bash-completion/completions/$name.bash

mkdir -p /usr/local/share/fish/vendor_completions.d 
ln -fbs $name.fish /usr/local/share/fish/vendor_completions.d/$name.fish

