#!/bin/bash

name=extract-chrome-cookies

cd $HOME

mkdir -p .$name

cd .$name

platform=''
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  platform=$name-linux-amd64.tar.gz
elif [[ "$OSTYPE" == "darwin"* ]]; then
  platform=$name-macos-amd64.tar.gz
        # Mac OSX
# elif [[ "$OSTYPE" == "cygwin" ]]; then
#         # POSIX compatibility layer and Linux environment emulation for Windows
# elif [[ "$OSTYPE" == "msys" ]]; then
#         # Lightweight shell and GNU utilities compiled for Windows (part of MinGW)
# elif [[ "$OSTYPE" == "win32" ]]; then
#         # I'm not sure this can happen.
# elif [[ "$OSTYPE" == "freebsd"* ]]; then
#         # ...
# else
        # Unknown.
fi

latest_version=$(curl -L -s -H 'Accept: application/json' https://github.com/lei4519/$name/releases/latest | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')

download_url=https://github.com/lei4519/$name/releases/download/$latest_version/$platform

curl -fsSLO $download_url

tar -xzf $platform

mkdir -p /usr/local/bin
ln -f -s $HOME/.$name/$name /usr/local/bin/$name

mkdir -p /usr/local/share/zsh/site-functions 
ln -f -s $HOME/.$name/_$name /usr/local/share/zsh/site-functions/_$name

mkdir -p /usr/local/share/bash-completion/completions 
ln -f -s $HOME/.$name/$name.bash /usr/local/share/bash-completion/completions/$name.bash

mkdir -p /usr/local/share/fish/vendor_completions.d 
ln -f -s $HOME/.$name/$name.fish /usr/local/share/fish/vendor_completions.d/$name.fish

if test -x $HOME/.fig 
then
  mkdir -p $HOME/.fig/autocomplete/build
  ln -f -s $HOME/.$name/$name.ts $HOME/.fig/autocomplete/build/$name.ts
fi

